server:
  port: 8090
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
    include: secret
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/blog_prod
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    com.ll.demo03: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  site:
    name: "My Site"